title = "AutoNata Experiments"

[irace]
exec = "./parallel-irace-mpi"

#[irace.foraging_nata1]
#args = "10 foraging_200kcat_nata1 --parallel 39 --max-experiments 200000 --scenario scenario_foraging.txt"
#
#[irace.foraging_nata2]
#args = "10 foraging_200kcat_nata2 --parallel 39 --max-experiments 200000 --scenario scenario_foraging_nata2.txt"
#
#[irace.dirgate_nata1]
#args = "10 dirgate_200kcat_nata1 --parallel 39 --max-experiments 200000 --scenario scenario_dirgate.txt"
#
#[irace.dirgate_nata2]
#args = "10 dirgate_200kcat_nata2 --parallel 39 --max-experiments 200000 --scenario scenario_dirgate_nata2.txt"
#
#[irace.xor2_nata1]
#args = "10 xor2_200kcat_nata1 --parallel 39 --max-experiments 200000 --scenario scenario_xor2.txt"
#
#[irace.xor2_nata2]
#args = "10 xor2_200kcat_nata2 --parallel 39 --max-experiments 200000 --scenario scenario_xor2_nata2.txt"

# pruned rep

[irace.foraging_nata1]
args = "10 foraging_200kcat_nata1_pru8 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_eight.rep350/ --max-experiments 200000 --scenario scenario_foraging.txt -p ./example/grammar_rep500g_236_cat_nata1.txt"

[irace.foraging_nata2]
args = "10 foraging_200kcat_nata2_pru8 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_eight.rep350/ --max-experiments 200000 --scenario scenario_foraging_nata2.txt -p ./example/grammar_rep500g_236_cat_nata2.txt"

[irace.dirgate_nata1]
args = "10 dirgate_200kcat_nata1_pru8 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_eight.rep350/ --max-experiments 200000 --scenario scenario_dirgate.txt -p ./example/grammar_rep500g_236_cat_nata1.txt"

[irace.dirgate_nata2]
args = "10 dirgate_200kcat_nata2_pru8 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_eight.rep350/ --max-experiments 200000 --scenario scenario_dirgate_nata2.txt -p ./example/grammar_rep500g_236_cat_nata2.txt"

[irace.xor2_nata1]
args = "10 xor2_200kcat_nata1_pru8 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_eight.rep350/ --max-experiments 200000 --scenario scenario_xor2.txt -p ./example/grammar_rep500g_236_cat_nata1.txt"

[irace.xor2_nata2]
args = "10 xor2_200kcat_nata2_pru8 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_eight.rep350/ --max-experiments 200000 --scenario scenario_xor2_nata2.txt -p ./example/grammar_rep500g_236_cat_nata2.txt"



[irace.foraging_nata1_p4]
args = "10 foraging_200kcat_nata1_pru4 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_quarter.rep17/ --max-experiments 200000 --scenario scenario_foraging.txt -p ./example/grammar_rep500g_495_cat_nata1.txt"

[irace.foraging_nata2_p4]
args = "10 foraging_200kcat_nata2_pru4 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_quarter.rep17/ --max-experiments 200000 --scenario scenario_foraging_nata2.txt -p ./example/grammar_rep500g_495_cat_nata2.txt"

[irace.dirgate_nata1_p4]
args = "10 dirgate_200kcat_nata1_pru4 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_quarter.rep17/ --max-experiments 200000 --scenario scenario_dirgate.txt -p ./example/grammar_rep500g_495_cat_nata1.txt"

[irace.dirgate_nata2_p4]
args = "10 dirgate_200kcat_nata2_pru4 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_quarter.rep17/ --max-experiments 200000 --scenario scenario_dirgate_nata2.txt -p ./example/grammar_rep500g_495_cat_nata2.txt"

[irace.xor2_nata1_p4]
args = "10 xor2_200kcat_nata1_pru4 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_quarter.rep17/ --max-experiments 200000 --scenario scenario_xor2.txt -p ./example/grammar_rep500g_495_cat_nata1.txt"

[irace.xor2_nata2_p4]
args = "10 xor2_200kcat_nata2_pru4 --parallel 39 --rep /home/khasselmann/Arlequin/pruning/temp-pruned_repertoire_one_quarter.rep17/ --max-experiments 200000 --scenario scenario_xor2_nata2.txt -p ./example/grammar_rep500g_495_cat_nata2.txt"

